location = /rollboard {
    return 302 /rollboard/;
}

location ^~ /rollboard/api/ {
    auth_basic "SEU Rollboard";
    auth_basic_user_file /mnt/domjudge/rollboard/secrets/htpasswd;

    proxy_pass http://127.0.0.1:18090;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
}

location ^~ /rollboard/data/ {
    auth_basic "SEU Rollboard";
    auth_basic_user_file /mnt/domjudge/rollboard/secrets/htpasswd;

    alias /mnt/domjudge/rollboard/www/data/;
    default_type application/json;
    add_header Cache-Control "no-store";
    try_files $uri =404;
}

location ^~ /rollboard/admin/ {
    auth_basic "SEU Rollboard";
    auth_basic_user_file /mnt/domjudge/rollboard/secrets/htpasswd;

    alias /mnt/domjudge/rollboard/www/admin/;
    index index.html;
    add_header Cache-Control "no-store";
    try_files $uri $uri/ /rollboard/admin/index.html;
}

location ^~ /rollboard/ {
    auth_basic "SEU Rollboard";
    auth_basic_user_file /mnt/domjudge/rollboard/secrets/htpasswd;

    alias /mnt/domjudge/rollboard/www/;
    index index.html;
    try_files $uri $uri/ /rollboard/index.html;
}
