x-judgehost-common: &judgehost-common
  image: domjudge/judgehost:9.0.0
  restart: unless-stopped
  privileged: true
  depends_on:
    - domserver
  networks:
    - dj-net
  env_file:
    - ./env.example
  environment: &judgehost-environment
    CONTAINER_TIMEZONE: Asia/Singapore
    DOMSERVER_BASEURL: http://dj-domserver/
    JUDGEDAEMON_USERNAME: judgehost
    JUDGEDAEMON_PASSWORD_FILE: /run/secrets/judgehost_password
    DOMJUDGE_CREATE_WRITABLE_TEMP_DIR: "0"
    RUN_USER_UID_GID: "62860"
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:rw
    - /mnt/domjudge/domjudge-live/secrets:/run/secrets:ro
    - /mnt/domjudge/domjudge-live/judgehost/judgings:/opt/domjudge/judgehost/judgings
    - /mnt/domjudge/domjudge-live/judgehost/log:/opt/domjudge/judgehost/log
    - /mnt/domjudge/domjudge-live/judgehost/tmp:/opt/domjudge/judgehost/tmp

services:
  mariadb:
    image: mariadb:latest
    container_name: dj-mariadb
    restart: unless-stopped
    networks:
      - dj-net
    env_file:
      - ./env.example
    environment:
      MYSQL_DATABASE: domjudge
      MYSQL_USER: domjudge
    volumes:
      - /mnt/domjudge/domjudge-live/mariadb:/var/lib/mysql

  domserver:
    image: domjudge/domserver:9.0.0
    container_name: dj-domserver
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - dj-net
    ports:
      - "127.0.0.1:12345:80"
    env_file:
      - ./env.example
    environment:
      CONTAINER_TIMEZONE: Asia/Singapore
      MYSQL_HOST: dj-mariadb
      MYSQL_DATABASE: domjudge
      MYSQL_USER: domjudge
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      DJ_DB_INSTALL_BARE: "0"
      WEBAPP_BASEURL: /
    volumes:
      - /mnt/domjudge/domjudge-live/secrets:/run/secrets:ro
      - /mnt/domjudge/domjudge-live/domserver:/opt/domjudge/domserver

  judgehost-0:
    <<: *judgehost-common
    container_name: dj-judgehost-0
    hostname: dj-judgehost-0
    environment:
      <<: *judgehost-environment
      DAEMON_ID: "0"

  judgehost-1:
    <<: *judgehost-common
    container_name: dj-judgehost-1
    hostname: dj-judgehost-1
    environment:
      <<: *judgehost-environment
      DAEMON_ID: "1"

  judgehost-2:
    <<: *judgehost-common
    container_name: dj-judgehost-2
    hostname: dj-judgehost-2
    environment:
      <<: *judgehost-environment
      DAEMON_ID: "2"

  judgehost-3:
    <<: *judgehost-common
    container_name: dj-judgehost-3
    hostname: dj-judgehost-3
    environment:
      <<: *judgehost-environment
      DAEMON_ID: "3"

networks:
  dj-net:
    name: dj-net
